Building up uninstaller
git-svn-id: http://svn.dojotoolkit.org/src@8045 560b804f-0ae3-0310-86f3-f6aa0a117693

diff --git a/branches/dot/src/dot/install-src/mac/pkg/DotApp-0.4.2.1/extras/preupgrade b/branches/dot/src/dot/install-src/mac/pkg/DotApp-0.4.2.1/extras/preupgrade
--- a/branches/dot/src/dot/install-src/mac/pkg/DotApp-0.4.2.1/extras/preupgrade
+++ b/branches/dot/src/dot/install-src/mac/pkg/DotApp-0.4.2.1/extras/preupgrade
@@ -1,5 +1,20 @@
 #!/bin/sh
 
-echo "$SCRIPT_NAME: running" >> /tmp/dot_install.log
+echo "$SCRIPT_NAME: Running" >> /tmp/dot_install.log 2>&1
+
+# first, uninstall the old installation
+echo "$SCRIPT_NAME: Uninstalling old installation..." >> /tmp/dot_install.log 2>&1
+/Applications/Dojo\ Offline\ Toolkit/Uninstall.sh
+if test $? -ne 0; then
+	echo "$SCRIPT_NAME: Unable to uninstall old installation" >> /tmp/dot_install.log 2>&1
+	exit 1
+fi
+
+# now install the new installation
+$PACKAGE_PATH/Contents/Resources/preinstall
+if test $? -ne 0; then
+	echo "$SCRIPT_NAME: Unable to install Dojo Offline" >> /tmp/dot_install.log 2>&1
+	exit 1
+fi
 
 exit 0
